### ISSUE TITLE
Timestamps Saving Incorrect Times

### ISSUE THREAD

**Issue by dkushner** [notheotherben/node-orm-timestamps#3]
Using package version 0.1.1, node version 0.10.17 and postgres version 9.1.9 I'm experiencing an issue with incorrect timestamps. 

I changed nothing from the default configuration for the package and yet timestamps still appear to be exactly 7 hours ahead of local time. For instance, `new Date()` reports the correct time at `Thu Sep 05 2013 09:11:14 GMT-0700 (PDT)`. Running `SELECT NOW()` on my postgres instance also returns the expected time PDT. However, creating and saving a timestamped ORM model instance and then immediately reloading it gives it a `created_at` property of `Thu Sep 05 2013 16:11:14 GMT-0700 (PDT)` which is not PDT but GMT-0. 

If `new Date()` is the default source of date and time information for timestamps, why are my timestamps in GMT-0?

**Comment by notheotherben** [comment]
Hey man, afraid this is actually an issue with ORM. We're busy fixing it now on the master branch, and you can follow the progress of this bug [here](/dresende/node-orm2/issues/303).

**Comment by dkushner** [comment]
Thanks for the quick reply. I actually commented on this in that issue as well, but I'm fairly certain the only problem here is that date objects are being stored in the database as "timestamp without time zone" instead of "timestamp with time zone" or "timestamptz." This seems to be corroborated by the later comments in [this](https://github.com/dresende/node-orm2/pull/325) pull request.

**Comment by notheotherben** [comment]
Unfortunately, ORM abstracts such details away from the interfaces. You can take a look at the plugin code and see that the _created_at_ and _updated_at_ properties are declared as `{ type: 'date', time: true }`. We're planning on having some kind of standardized handling within ORM for date storage since MySQL and some other database engines don't have explicit support for timezones. If there are changes to the ORM API for this I will make sure that the plugin is updated.

**Comment by dkushner** [comment]
Excellent, thanks so much for the clarification.
